#include "DataFormats/Portable/interface/PortableHostCollectionReadRules.h"
#include "DataFormats/PyTorchTest/interface/Host.h"

SET_PORTABLEHOSTCOLLECTION_READ_RULES(ParticleCollectionHost);
SET_PORTABLEHOSTCOLLECTION_READ_RULES(ClassificationCollectionHost);
SET_PORTABLEHOSTCOLLECTION_READ_RULES(RegressionCollectionHost);
